# WAFIR Configuration Example - GitHub Projects
# Stores feedback as GitHub Project items for kanban-style tracking
# Place this file in .github/wafir.yaml in your repository

# Storage settings - store as project items
storage:
  type: issue

# Feedback modal settings
feedback:
  title: "Submit Feedback"
  labels: ["wafir"]

# Automatic data collection
issue:
  screenshot: true
  browserInfo: true
  consoleLog: false
  labels: ["feedback"]

# Form fields mapped to project columns/fields
fields:
  - name: title
    label: "Summary"
    type: text
    required: true

  - name: description
    label: "Details"
    type: textarea
    required: true

  - name: type
    label: "Type"
    type: select
    options: ["Bug", "Feature Request", "Improvement", "Question"]
    required: true
    
