# WAFIR Configuration Example - Feedback Only
# Collects user satisfaction ratings instead of bug reports
# Place this file in .github/wafir.yaml in your repository

# Widget mode - both issue reporting AND star ratings
mode: both

# Storage settings (feedback stored as issues with different labels)
storage:
  type: issue

# Dedicated project for feedback with rating field
# Follow setup guide to create Rating field with star emoji options (⭐, ⭐⭐, etc.)
feedbackProject:
  projectNumber: 1 # Your feedback project number
  ratingField: "Rating" # Name of the Rating field in your project

# Feedback modal settings
feedback:
  title: "How are we doing?"
  labels: ["feedback", "user-satisfaction"]

# Form fields - these will be shown after the star rating
fields:
  - name: title
    label: "What's on your mind?"
    type: text
    required: false

  - name: comment
    label: "Tell us more (optional)"
    type: textarea
    required: false
